### ISSUE TITLE
dhcp error

### ISSUE THREAD

**Issue by RotFarm** [dividebysandwich/shareboxx#5]
After installing dhcpcd, I'm still getting the error "dhcpcd has no installation candidate" Not sure what to do from here. 

It happens when I try to install ./enable-captive-portal.sh

**Comment by dividebysandwich** [comment]
Which OS are you on? You say you installed dhcpcd? Can you run it? If so, you could just remove the part of the script that tries to install it. But it feels weird. I definitely need a bit more info, like linux distro and version, console output of what you tried, etc.
Did you try to run ```apt update``` ?

**Comment by RotFarm** [comment]
Ubuntu 22.04 (it is also running on a nintendo switch for better context) it's a modified version, but really wanted the sort of mobile experience like your U-Console.

I got it to run as root, but on trying it again I'm still getting the same error "no installation candidate.'

``Hit:1 https://Pi-Apps-Coders.github.io/box64-debs/debian ./ InRelease
Hit:2 https://Pi-Apps-Coders.github.io/box86-debs/debian ./ InRelease                                                                      
Hit:3 https://theofficialgman.github.io/l4t-debs l4t InRelease                                                                             
Hit:4 https://repo.steampowered.com/steam stable InRelease                                                                                 
Get:5 https://dl.cloudsmith.io/public/moonlight-game-streaming/moonlight-l4t/deb/ubuntu bionic InRelease [3,674 B]                         
Hit:6 http://ports.ubuntu.com/ubuntu-ports jammy InRelease                                                    
Hit:7 http://ports.ubuntu.com/ubuntu-ports jammy-updates InRelease                                            
Hit:8 http://ports.ubuntu.com/ubuntu-ports jammy-backports InRelease             
Hit:9 http://ports.ubuntu.com/ubuntu-ports jammy-security InRelease              
Hit:10 https://ppa.launchpadcontent.net/git-core/ppa/ubuntu jammy InRelease
Hit:11 https://ppa.launchpadcontent.net/kisak/kisak-mesa/ubuntu jammy InRelease
Hit:12 https://ppa.launchpadcontent.net/theofficialgman/gpu-tools/ubuntu jammy InRelease
Hit:13 https://ppa.launchpadcontent.net/ubuntu-mozilla-security/ppa/ubuntu jammy InRelease
Fetched 3,674 B in 2s (1,562 B/s)
Reading package lists... Done
N: Skipping acquire of configured file 'main/binary-armhf/Packages' as repository 'https://dl.cloudsmith.io/public/moonlight-game-streaming/moonlight-l4t/deb/ubuntu bionic InRelease' doesn't support architecture 'armhf'
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
nala is already the newest version (0.11.1~bpo22.04.1).
0 upgraded, 0 newly installed, 0 to remove and 6 not upgraded.
Error: dhcpcd has no installation candidate.
Failed to stop dnsmasq.service: Unit dnsmasq.service not loaded.
Failed to stop hostapd.service: Unit hostapd.service not loaded.
Unit dnsmasq.service does not exist, proceeding anyway.
Failed to enable unit: Unit file dnsmasq.service does not exist.
Failed to restart dnsmasq.service: Unit dnsmasq.service not found.
./enable-captive-portal.sh: 47: netfilter-persistent: not found
cp: cannot create regular file '/etc/hostapd/hostapd.conf': No such file or directory
Unit hostapd.service does not exist, proceeding anyway.
Failed to enable unit: Unit file hostapd.service does not exist.
Failed to start hostapd.service: Unit hostapd.service not found.
``

**Comment by dividebysandwich** [comment]
Hmm, maybe Ubuntu doesn't have a package for armhf? You could always install dhcpcd from source instead...

**Comment by RotFarm** [comment]
I think I found the kink. Ubuntu doesn't have architecture for armhf, so I'd have to install it.

**Comment by dividebysandwich** [comment]
Aye, looks like it. As I wrote before, I'd recommend installing that from source, might be easiest.
I'll close this bug for now.
