### ISSUE TITLE
No landing page/captive portal 

### ISSUE THREAD

**Issue by de-mon** [dividebysandwich/shareboxx#6]
Followed the directions and I assumed everyting went as planned. But, I was never able to connect to the landing page (on an ipad via chrome and safari) even when I attempted to use http://share.lan

Also, after a reboot, the access point did not start until I reran the "./enable-captive-portal.sh" script. 

I did set this up as root instead of my standard user. not sure it that makes a difference

I really appreciate the work you've done. I miss my Pirate Box

**Comment by dividebysandwich** [comment]
Could you please run it directly and get me the console output?

**Comment by de-mon** [comment]
I started from scratch and got the access point to work.. but still no page. I did notice a couple of errors during the build. (see attached) 
Raspi-OS 64 bit - 
Pi 4 with 4 GB ram
Ethernet cable. 
Used Pi Imager to set user name, password and enable ssh. 
built from remote computer over ssh
installed mc, nala and git 
installed Rust  _curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh_
cloned into _/home/[user]_
ran _cargo install cargo-leptos&&cargo leptos build --release_ and got this error in the screenshot
![shareboxx-1](https://github.com/user-attachments/assets/7aece88b-f84f-4225-bc35-a3322c35bd24)

cd to _/shareboxx/access-point_
ran _sudo ./enable-captive-portal.sh_ and received this error
![Screenshot 2024-07-13 132813](https://github.com/user-attachments/assets/311aab2a-3746-4ecc-9110-96a0982ad2d8)

ran the other scripts with no errors or issues. 
AP came right up, was able to connect. 

I know I'm doing something stupid that I'm missing.

**Comment by dividebysandwich** [comment]
You are not in the shareboxx directory? Before you run "cargo leptos build" make sure you are in the shareboxx dir, that is the one you cloned from git and that has Cargo.toml in ot

**Comment by de-mon** [comment]
got it... I'll try again

**Comment by de-mon** [comment]
It worked! 100% user Error.. closing issue
