### ISSUE TITLE
Consider Upgrading sharboxx to APGL v3

### ISSUE THREAD

**Issue by i-walker** [dividebysandwich/shareboxx#7]
# Consider Upgrading shareboxx to AGPL v3

## Summary
A propose upgrading the license of shareboxx from GPL v2 to AGPL v3 to better protect the interests of the project and its community in the age of cloud computing and network-based software deployment.

## Background
shareboxx is currently licensed under GPL v2, which has served the project well. However, the software landscape has evolved significantly since GPL v2 was drafted, particularly with the rise of cloud computing and SaaS models.

## Rationale for Upgrade

1. **Network Use Provision**: AGPL v3 includes a "network use" clause that requires users who modify and run the software to provide a network service to make their modifications available. This ensures that improvements to shareboxx remain open source even when deployed as a network service.

2. **Patent Protection**: AGPL v3 provides explicit patent protection, requiring contributors to provide a patent license along with their code contributions. This can help protect the project and its users from potential patent litigation.

3. **Modernized License**: AGPL v3 addresses modern concerns such as DRM and hardware restrictions, which were not as prevalent when GPL v2 was written.

4. **Compatibility**: While AGPL v3 is not directly compatible with GPL v2, it is compatible with GPL v3 and other modern open source licenses, potentially allowing for easier collaboration with other projects.

## Long-term Impact on the Community

1. **Preservation of Open Source Ethos**: Ensuring that modifications to shareboxx remain open source, even when used in network services, upholds the spirit of free and open source software.

2. **Encouraging Contributions**: By requiring network service providers to share their modifications, we may see increased contributions back to the main project, benefiting all users.

3. **Future-proofing**: As more software moves to cloud and network-based deployments, AGPL v3 helps ensure that shareboxx remains truly open in these new environments.

4. **Legal Clarity**: The updated license provides clearer terms for modern use cases, potentially reducing legal ambiguities for users and contributors.

## Potential Challenges

1. **License Incompatibility**: Some existing GPL v2 code may not be compatible with AGPL v3. A thorough code review would be necessary.

2. **Community Acceptance**: Some contributors or users may have concerns about the more restrictive nature of AGPL v3.

3. **Relicensing Process**: Obtaining permission from all contributors to relicense their code could be a significant undertaking.

## Disclaimer
While I've researched this topic thoroughly, I'm no lawyer, and this doesn't constitute my legal capabilities. The purpose of this issue is to start a constructive discussion about the potential benefits and challenges of upgrading shareboxx to AGPL v3.

## Next Steps
1. Gather community feedback on this proposal
2. If necessary, consult with legal experts on the implications and process of license upgrading
3. If decided to proceed, create a plan for the relicensing process

Looking forward to a friendly and productive discussion on this topic. ☺️
Feedback and concerns are highly valued and welcome as we consider the future of shareboxx.

P.S.: Thanks a lot for your awesome project @dividebysandwich

**Comment by dividebysandwich** [comment]
Hi, I honestly don't think shareboxx needs to worry about cloud providers stealing our thunder or anything like that. For one, this is a local-only project and anyone deploying this as a service on the internet is in for a lot of trouble. Another factor is that shareboxx doesn't actually do all that much. You could achieve the same with some php code and a bit of html, I just wanted to learn more about Rust web frameworks and get a nice single server binary in the process.

I am not saying you should not care about SaaS providers at all - I am all for using a more suitable license in case your project could potentially earn someone else millions without them having to give anything back. I'm just not sure shareboxx falls into that category.

Lastly, I am acutely aware of the issues surrounding the GPL and similar licenses. My personal opinion, as someone who has contributed to projects that are now part of distros such as RHEL, is that no new license will fix the major issue of GPLv2, v3 and other licenses: Lack of enforcement.  It is my personal opinion that RedHat/IBM most likely violate a number of licenses by restricting the redistribution of sourcecode that has been provided to RedHat under these licenses. This will not go away until they are taken to court and either made to obey the license again, or having their access to said code revoked. My hope is that sometime in the next few years, this legal process will begin.

**Comment by i-walker** [comment]
Thanks for your feedback :)
I’ll close this issue .
